FROM authelia:latest
RUN mkdir /config/secrets && \
    touch /config/secrets/authelia_jwt_secret && \
    echo ${AUTHELIA_JWT_SECRET} >> /config/secrets/authelia_jwt_secret && \
    touch /config/secrets/authelia_session_secret && \
    echo ${AUTHELIA_SESSION_SECRET} >> /config/secrets/authelia_session_secret && \
    chmod -R 600 /config/secrets