version: "3"
services:
  traefik:
    build:
      context: .
      dockerfile: dockerfile.traefik
      args:
        DOMAIN_1: ${DOMAIN_1}
        DOMAIN_2: ${DOMAIN_2}
    container_name: "traefik"
    command:
      - "--certificatesresolvers.dns-cloudflare.acme.email=${CF_API_EMAIL}"
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/rules:/rules:ro"
      - "./shared:/shared:ro"      
      - "./traefik/traefik.yml:/traefik.yml:ro"
      - "./traefik/logs:/logs:rw"
    labels:
      # Enable
      - "traefik.enable=true"      
      # Global http-->https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=wwwtohttps"
      # Global wwwhttps-->https
      - "traefik.http.routers.wwwsecure-catchall.rule=hostregexp(`{host:(www\\.).+}`)"
      - "traefik.http.routers.wwwsecure-catchall.entrypoints=https"
      - "traefik.http.routers.wwwsecure-catchall.tls=true"
      - "traefik.http.routers.wwwsecure-catchall.middlewares=wwwtohttps"
      # middleware: http(s)://(www.) to  https://
      - "traefik.http.middlewares.wwwtohttps.redirectregex.regex=^(?:http|https)://(?:www\\.)?(.*)"
      - "traefik.http.middlewares.wwwtohttps.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.wwwtohttps.redirectregex.permanent=true"
      # API
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.rule=Host(`api.${DOMAIN_1}`)"
      # Services - API
      - "traefik.http.routers.api.service=api@internal"
      # Middlewares
      - "traefik.http.routers.api.middlewares=middlewares-basic-auth@file"
      - "traefik.http.routers.api.middlewares=authelia"
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://login.${DOMAIN_1}/"
      - "traefik.http.middlewares.authelia.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authresponseheaders=Remote-User, Remote-Groups"
      # Wildcard cert
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.api.tls.domains[0].main=${DOMAIN_1}"
      - "traefik.http.routers.api.tls.domains[0].sans=*.${DOMAIN_1}"
      - "traefik.http.routers.api.tls.domains[1].main=${DOMAIN_2}"
      - "traefik.http.routers.api.tls.domains[1].sans=*.${DOMAIN_2}"
  authelia:
    build:
      context: .
      dockerfile: dockerfile.authelia
    container_name: "authelia"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DOMAIN_1=${DOMAIN_1}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret       
    volumes:
      - ./authelia:/config
      - ./authelia/secrets:/run/secrets:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia-https.rule=Host(`login.${DOMAIN_1}`)"     
      - "traefik.http.routers.authelia-https.entrypoints=https"
      - "traefik.http.routers.authelia-https.tls=true"
      - "traefik.http.routers.authelia-https.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"
  daux:
    build:
      context: .
      dockerfile: dockerfile.daux
    container_name: "daux"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daux.tls=true"
      - "traefik.http.routers.daux.entrypoints=https"
      - "traefik.http.routers.daux.rule=Host(`docs.${DOMAIN_1}`)"
  web:
    image: tobilg/mini-webserver:latest
    container_name: "web"
    volumes:
      - ./${DOMAIN_1}:/app/public:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.entrypoints=https"
      - "traefik.http.routers.web.rule=Host(`${DOMAIN_1}`)"