FROM authelia/authelia:4
RUN mkdir /run/secrets && \
    touch /run/secrets/authelia_jwt_secret && \
    echo ${AUTHELIA_JWT_SECRET} >> /run/secrets/authelia_jwt_secret && \
    touch /config/secrets/authelia_session_secret && \
    echo ${AUTHELIA_SESSION_SECRET} >> /run/secrets/authelia_session_secret && \
    chmod -R 600 /run/secrets