api:
 dashboard: true
global:
  sendAnonymousUsage: false
pilot:
  token:
entryPoints:
  http:
    address: ":80"
    # forwardedHeaders:
    #   trustedIPs:
    #     - 127.0.0.1/32
    #     - 192.168.0.0/16
    #     - 172.16.0.0/12
    #     - 10.0.0.0/8
    #     - "103.21.244.0/22"
    #     - "103.22.200.0/22"
    #     - "103.31.4.0/22"
    #     - "141.101.64.0/18"
    #     - "108.162.192.0/18"
    #     - "190.93.240.0/20"
    #     - "188.114.96.0/20"
    #     - "197.234.240.0/22"
    #     - "198.41.128.0/17"
    #     - "162.158.0.0/15"
    #     - "104.16.0.0/12"
    #     - "172.64.0.0/13"
    #     - "131.0.72.0/22"        
  https:
    address: ":443"
    middlewares:
      no-www:
        redirectScheme:
          permanent: true
          regex: "^https://www.(.*)"
          replacement: "https://$1"
    # forwardedHeaders:
    #   trustedIPs:
    #     - "127.0.0.1/32"
    #     - "192.168.0.0/16"
    #     - "172.16.0.0/12"
    #     - "10.0.0.0/8"
    #     - "103.21.244.0/22"
    #     - "103.22.200.0/22"
    #     - "103.31.4.0/22"
    #     - "141.101.64.0/18"
    #     - "108.162.192.0/18"
    #     - "190.93.240.0/20"
    #     - "188.114.96.0/20"
    #     - "197.234.240.0/22"
    #     - "198.41.128.0/17"
    #     - "162.158.0.0/15"
    #     - "104.16.0.0/12"
    #     - "172.64.0.0/13"
    #     - "131.0.72.0/22"
    # proxyProtocol:
    #   trustedIPs:
    #     - "127.0.0.1/32"
    #     - "192.168.1.1"
    #     - "173.245.48.0/20"
    #     - "103.21.244.0/22"
    #     - "103.22.200.0/22"
    #     - "103.31.4.0/22"
    #     - "141.101.64.0/18"
    #     - "108.162.192.0/18"
    #     - "190.93.240.0/20"
    #     - "188.114.96.0/20"
    #     - "197.234.240.0/22"
    #     - "198.41.128.0/17"
    #     - "162.158.0.0/15"
    #     - "104.16.0.0/12"
    #     - "172.64.0.0/13"
    #     - "131.0.72.0/22"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
#    defaultRule: "Host(`{{ index .Labels \"com.docker.compose.service\"}}.${DOMAIN_1}`)"
#    network: network
  file:
    directory: "/rules"
    watch: true
certificatesResolvers:
  # http:
  #   acme:
  #     email: #CloudFlare Email
  #     storage: /etc/traefik/acme.json
  #     httpChallenge:
  #       entryPoint: http
  dns-cloudflare:
    acme:
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
serversTransport:
    insecureSkipVerify: true
accessLog:
  filePath: "/logs/traefik/access.log"
  fields:
    headers:
      names:
        User-Agent: keep
log:
  level: DEBUG