[http.middlewares]
  [http.middlewares.middlewares-basic-auth]
    [http.middlewares.middlewares-basic-auth.basicAuth]
#      username=user, password=password (listed below after hashing)
#      users = [
#        "user:$apr1$bvj3f2o0$/01DGldkkluxK4AqRsTwHnvc1",
#      ]
      realm = "Traefik2 Basic Auth"
      usersFile = "/shared/.htpasswd" #be sure to mount the volume through docker-compose.yml
  [http.middlewares.nonwwwhttps]
    [http.middlewares.nonwwwhttps.redirectregex]
      regex = ^https?://(?:www\.)?(.+)
      replacement = https://$${1}
      permanent = true